### ISSUE TITLE
Does this work with JHipster 4.5.3?

### ISSUE THREAD

**Issue by TBarina** [hipster-labs/generator-jhipster-entity-audit#61]
Hi, I'm trying to use this generator with JHipster 4.5.3 (Running Spring Boot 1.5.4.RELEASE) with MySQL DB.

I get various BUILD FAILURE errors.

I investigated the code and there are some issues like the following that I can point out:

-  AsyncEntityAuditEventWriter class in config.audit (as well as EntityAuditResource in web.rest) make use of @Inject instead of @Autowired (and this causes error since javax.inject.Inject has been removed from JHipster generator);
- EntityAuditEvent class is added in the domain but has a "private **ZonedDateTime** modifiedDate" attribute which is not compatible with created_date and lastModifiedDate in AbstractAuditingEntity class (AbstractAuditingEntity attributes are of type **Instant** and this cause the following Compilation Errors:
_AsyncEntityAuditEventWriter.java:[82,77] incompatible types: java.time.Instant cannot be converted to java.time.ZonedDateTime 
and 
AsyncEntityAuditEventWriter.java:[86,82] incompatible types: java.time.Instant cannot be converted to java.time.ZonedDateTime_).

Even if I try and fix those issues I get this error:

:: JHipster 🤓  :: Running Spring Boot 1.5.4.RELEASE ::
:: http://jhipster.github.io ::

2017-06-14 16:04:34.197  INFO 3922 --- [  restartedMain] com.tbit.jhbase.TBitJhTest01App          : Starting TBitJhTest01App on centos7_dev01.tbit.local with PID 3922 (/home/io/workspace_neon/_TBit_JH_Test01/target/classes started by io in /home/io/workspace_neon/_TBit_JH_Test01)
2017-06-14 16:04:34.200 DEBUG 3922 --- [  restartedMain] com.tbit.jhbase.TBitJhTest01App          : Running with Spring Boot v1.5.4.RELEASE, Spring v4.3.9.RELEASE
2017-06-14 16:04:34.201  INFO 3922 --- [  restartedMain] com.tbit.jhbase.TBitJhTest01App          : The following profiles are active: swagger,dev
2017-06-14 16:04:34.779 DEBUG 3922 --- [kground-preinit] org.jboss.logging                        : Logging Provider: org.jboss.logging.Slf4jLoggerProvider found via system property
2017-06-14 16:04:38.199 DEBUG 3922 --- [  restartedMain] c.tbit.jhbase.config.AsyncConfiguration  : Creating Async Task Executor
2017-06-14 16:04:39.532 DEBUG 3922 --- [  restartedMain] c.e.c.E.tbit.jhbase.domain.User          : Initialize successful.
2017-06-14 16:04:39.575 DEBUG 3922 --- [  restartedMain] c.e.c.E.tbit.jhbase.domain.Authority     : Initialize successful.
2017-06-14 16:04:39.592 DEBUG 3922 --- [  restartedMain] c.e.c.E.t.j.domain.User.authorities      : Initialize successful.
2017-06-14 16:04:39.599 DEBUG 3922 --- [  restartedMain] c.e.c.E.t.jhbase.domain.PersistentToken  : Initialize successful.
2017-06-14 16:04:39.604 DEBUG 3922 --- [  restartedMain] c.e.c.E.t.j.d.User.persistentTokens      : Initialize successful.
2017-06-14 16:04:39.610 DEBUG 3922 --- [  restartedMain] c.e.c.E.t.j.d.E.persistentTokens         : Initialize successful.
2017-06-14 16:04:40.039 DEBUG 3922 --- [  restartedMain] c.t.jhbase.config.MetricsConfiguration   : Registering JVM gauges
2017-06-14 16:04:40.062 DEBUG 3922 --- [  restartedMain] c.t.jhbase.config.MetricsConfiguration   : Monitoring the datasource
2017-06-14 16:04:40.063 DEBUG 3922 --- [  restartedMain] c.t.jhbase.config.MetricsConfiguration   : Initializing Metrics JMX reporting
2017-06-14 16:04:41.293 DEBUG 3922 --- [  restartedMain] com.tbit.jhbase.config.WebConfigurer     : Registering CORS filter
2017-06-14 16:04:41.534  INFO 3922 --- [  restartedMain] com.tbit.jhbase.config.WebConfigurer     : Web application configuration, using profiles: swagger
2017-06-14 16:04:41.535 DEBUG 3922 --- [  restartedMain] com.tbit.jhbase.config.WebConfigurer     : Initializing Metrics registries
2017-06-14 16:04:41.540 DEBUG 3922 --- [  restartedMain] com.tbit.jhbase.config.WebConfigurer     : Registering Metrics Filter
2017-06-14 16:04:41.541 DEBUG 3922 --- [  restartedMain] com.tbit.jhbase.config.WebConfigurer     : Registering Metrics Servlet
2017-06-14 16:04:41.547  INFO 3922 --- [  restartedMain] com.tbit.jhbase.config.WebConfigurer     : Web application fully configured
2017-06-14 16:04:41.998 DEBUG 3922 --- [  restartedMain] c.t.jhbase.config.DatabaseConfiguration  : Configuring Liquibase
2017-06-14 16:04:42.021  WARN 3922 --- [t-01-Executor-1] i.g.j.c.liquibase.AsyncSpringLiquibase   : Starting Liquibase asynchronously, your database might not be ready at startup!
2017-06-14 16:04:43.998  WARN 3922 --- [  restartedMain] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory
2017-06-14 16:04:44.056 DEBUG 3922 --- [  restartedMain] c.e.c.E.t.j.d.User.persistentTokens      : Close successful.
2017-06-14 16:04:44.057 DEBUG 3922 --- [  restartedMain] c.e.c.E.t.jhbase.domain.PersistentToken  : Close successful.
2017-06-14 16:04:44.058 DEBUG 3922 --- [  restartedMain] c.e.c.E.t.j.d.E.persistentTokens         : Close successful.
2017-06-14 16:04:44.059 DEBUG 3922 --- [  restartedMain] c.e.c.E.tbit.jhbase.domain.Authority     : Close successful.
2017-06-14 16:04:44.063 DEBUG 3922 --- [  restartedMain] c.e.c.E.t.j.domain.User.authorities      : Close successful.
2017-06-14 16:04:44.066 DEBUG 3922 --- [  restartedMain] c.e.c.E.tbit.jhbase.domain.User          : Close successful.
2017-06-14 16:04:44.093  WARN 3922 --- [t-01-Executor-1] com.zaxxer.hikari.pool.ProxyConnection   : HikariPool-1 - Connection com.mysql.jdbc.JDBC4Connection@78d7856a marked as broken because of SQLSTATE(08003), ErrorCode(0)

com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:918)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:897)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:886)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:860)
	at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1187)
	at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1182)
	at com.mysql.jdbc.ConnectionImpl.rollback(ConnectionImpl.java:4505)
	at com.zaxxer.hikari.pool.ProxyConnection.rollback(ProxyConnection.java:360)
	at com.zaxxer.hikari.pool.HikariProxyConnection.rollback(HikariProxyConnection.java)
	at liquibase.database.jvm.JdbcConnection.rollback(JdbcConnection.java:337)
	at liquibase.database.AbstractJdbcDatabase.rollback(AbstractJdbcDatabase.java:1166)
	at liquibase.lockservice.StandardLockService.acquireLock(StandardLockService.java:205)
	at liquibase.lockservice.StandardLockService.waitForLock(StandardLockService.java:170)
	at liquibase.Liquibase.update(Liquibase.java:196)
	at liquibase.Liquibase.update(Liquibase.java:192)
	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:431)
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:388)
	at io.github.jhipster.config.liquibase.AsyncSpringLiquibase.initDb(AsyncSpringLiquibase.java:82)
	at io.github.jhipster.config.liquibase.AsyncSpringLiquibase.lambda$afterPropertiesSet$0(AsyncSpringLiquibase.java:64)
	at io.github.jhipster.async.ExceptionHandlingAsyncTaskExecutor.lambda$createWrappedRunnable$1(ExceptionHandlingAsyncTaskExecutor.java:66)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

2017-06-14 16:04:44.096  WARN 3922 --- [t-01-Executor-1] liquibase                                : Failed to restore the auto commit to true
2017-06-14 16:04:44.096 ERROR 3922 --- [t-01-Executor-1] i.g.j.c.liquibase.AsyncSpringLiquibase   : Liquibase could not start correctly, your database is NOT ready: java.sql.SQLException: Connection is closed

liquibase.exception.DatabaseException: java.sql.SQLException: Connection is closed
	at liquibase.database.jvm.JdbcConnection.setAutoCommit(JdbcConnection.java:363)
	at liquibase.database.AbstractJdbcDatabase.close(AbstractJdbcDatabase.java:1202)
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:397)
	at io.github.jhipster.config.liquibase.AsyncSpringLiquibase.initDb(AsyncSpringLiquibase.java:82)
	at io.github.jhipster.config.liquibase.AsyncSpringLiquibase.lambda$afterPropertiesSet$0(AsyncSpringLiquibase.java:64)
	at io.github.jhipster.async.ExceptionHandlingAsyncTaskExecutor.lambda$createWrappedRunnable$1(ExceptionHandlingAsyncTaskExecutor.java:66)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLException: Connection is closed
	at com.zaxxer.hikari.pool.ProxyConnection$ClosedConnection$1.invoke(ProxyConnection.java:468)
	at com.sun.proxy.$Proxy106.setAutoCommit(Unknown Source)
	at com.zaxxer.hikari.pool.ProxyConnection.setAutoCommit(ProxyConnection.java:378)
	at com.zaxxer.hikari.pool.HikariProxyConnection.setAutoCommit(HikariProxyConnection.java)
	at liquibase.database.jvm.JdbcConnection.setAutoCommit(JdbcConnection.java:361)
	... 8 common frames omitted

2017-06-14 16:04:44.105 ERROR 3922 --- [  restartedMain] o.s.boot.SpringApplication               : Application startup failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1628)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1078)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:857)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at com.tbit.jhbase.TBitJhTest01App.main(TBitJhTest01App.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.persistenceException(EntityManagerFactoryBuilderImpl.java:967)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:892)
	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:60)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:353)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:370)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:359)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1687)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624)
	... 19 common frames omitted
Caused by: java.lang.IllegalStateException: All Hibernate caches should be created upfront. Please update CacheConfiguration.java to add com.tbit.jhbase.domain.EntityAuditEvent
	at io.github.jhipster.config.jcache.NoDefaultJCacheRegionFactory.createCache(NoDefaultJCacheRegionFactory.java:37)
	at org.hibernate.cache.jcache.JCacheRegionFactory.getOrCreateCache(JCacheRegionFactory.java:190)
	at org.hibernate.cache.jcache.JCacheRegionFactory.buildEntityRegion(JCacheRegionFactory.java:113)
	at org.hibernate.cache.spi.RegionFactory.buildEntityRegion(RegionFactory.java:132)
	at org.hibernate.internal.CacheImpl.determineEntityRegionAccessStrategy(CacheImpl.java:439)
	at org.hibernate.metamodel.internal.MetamodelImpl.initialize(MetamodelImpl.java:120)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:297)
	at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:445)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:889)
	... 25 common frames omitted

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 18.362 s
[INFO] Finished at: 2017-06-14T16:04:44+02:00
[INFO] Final Memory: 34M/493M
[INFO] ------------------------------------------------------------------------

Anyone can help?

Many thanks in advance

**Comment by szmg** [comment]
Hi, this might help: #64

**Comment by TBarina** [comment]
Thanks, I've updated the generator and can confirm that it works now.
I have the same problem as in #61 though: when running entity audit module on an existing entity the generator creates new columns to the existing changelog of that entity, due to this liquibase throws database changelog validation error during the build.

Thanks again.

**Comment by deepu105** [comment]
This needs work to be able to work with latest generator. Any help will be appreciated as I dont have enough time
