### ISSUE TITLE
Javers compilation failure regarding Optionals

### ISSUE THREAD

**Issue by poolebu** [hipster-labs/generator-jhipster-entity-audit#79]
Jhipster version: `"generator-jhipster": "4.13.1"`

**[ERROR] ... Compilation failure
[ERROR] /src/main/java/com/catwizard/jenis/config/audit/JaversAuthorProvider.java:[13,59] incompatible types: java.util.Optional<java.lang.String> cannot be converted to java.lang.String**

![captura de pantalla 2017-12-29 a la s 1 21 16 p m](https://user-images.githubusercontent.com/4500001/34437053-352ab768-ec9b-11e7-9fe7-f798d470b7a9.png)

Note: I haven't used Optionals yet, I understand this is a Java 8 feature, which I'm using. Is this error related to my environment ?

**Comment by deepu105** [comment]
Provide details like .yo-rc.json file and module version used otherwise I cannot hep you

**Comment by ruddell** [comment]
SecurityUtils changed one month ago (v4.12.0+) to return Optionals instead of Strings https://github.com/jhipster/generator-jhipster/commit/b7e17569e7dcf1bc1a07c909a9466c7bffb49b98#diff-0d3112b00f14a90aa7d0063d173ff00a

**Comment by poolebu** [comment]
Here is the `.yo-rc.json`. @ruddell you think it will work on version prior to v4.12 ?
```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "io.catwizard.lingostand",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.8.2",
    "baseName": "lingostand",
    "packageName": "io.catwizard.lingostand",
    "packageFolder": "io/catwizard/lingostand",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "41c2ff3421b9e10f8acde39b740538b8f6fa5fa2",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "es"
    ]
  }
}
```

**Comment by ruddell** [comment]
For versions using v4.12+ I would change the function to return:
`return SecurityUtils.getCurrentUserLogin().orElse(Constants.SYSTEM_ACCOUNT);`

**Comment by poolebu** [comment]
Worked, Thank you!
![captura de pantalla 2017-12-29 a la s 7 17 20 p m](https://user-images.githubusercontent.com/4500001/34444252-ef22f1c2-eccc-11e7-824b-9fa223d09018.png)

**Comment by deepu105** [comment]
Entity audit module is not yet updated to reflect this change would you like to do a PR

**Comment by poolebu** [comment]
I would be honored yes :)

**Comment by pascalgrimaud** [comment]
You need to fork this project and clone your fork.
So you'll work locally on your fork.

**Comment by poolebu** [comment]
Duplicate of #80
